##### config.yml file use to configure applications ###
# 1: environments: Setup ip sniffing to detect environments 
environments:
  development:  172.*
  production:   86.54.101.70

# Environment configuration.
development:
 db:
  dbtype: none  
  host: localhost
  database: app_development
  username: root
  password: secret

test:
  db:
    dbtype: mysql
    host: localhost
    database: app_test
    username: root
    password: secret

production: 
  db: 
    dbtype: mysql
    host: localhost
    database: app_production
    username: root
    password: secret


# 2: route: passes config values to WXRoute
# options:
#  a) default:page -the value of default is the controller that unanswered requests are passed to
route:
  default: page
  urls:        
    "/^([\w-]*)\/([\w-]*)\/([\w-]*)/":   
      controller:
      action:
      id:

# 3: Automatic deploymet config for script/deploy
# Requires destination server, login and path and subversion user, password and path.
deploy:
  server:       example.com
  server_path:  /
  user:         appuser
  svn_user:
  svn_pass:
  svn_path:   
  before_deploy:
    # add any unix commands to be run on the remote server before deploy - 1 per line
  after_deploy:
    # add any unix commands to be run on the remote server after deploy - 1 per line

# 4: Maintenance downtime: Use to make the site unavailable to all but one ip
# Just comment the lines out to operate the site normally. Note that this will need to be your public ip address.
# Redirect gives an address to redirect all requests to.
#maintenance: 
#  ip:       123.456.7.8
#  redirect: holding

# 5: Asset Serving: Serve any public asset from a separate server : just the domain - no slashes
#assets: static.yoursite.com/
