##### config.yml file use to configure applications ###
# Environments: Setup ip sniffing to detect environments
# 
#  Hopefully entirely unnecessary most of the time - 
#  Local ranges 127., 10. and 192. default to development


# environments:
#   development:  172.*
#   production:   86.54.101.70



# == Database configuration ==
development:
 db:
  dbtype: none  
  host: localhost
  database: app_development
  username: root
  password: secret

test:
  db:
    dbtype: mysql
    host: localhost
    database: app_test
    username: root
    password: secret

production: 
  db: 
    dbtype: mysql
    host: localhost
    database: app_production
    username: root
    password: secret



# == Automatic deployment config for script/deploy ==
# Requires destination server, login and path and subversion path to checkout from.
#
# Note that this is only for basic deployment, we'd advise using capistrano where available
# There should be an example capfile in the root of your application.

deploy:
  server:       example.com
  server_path:  /
  user:         appuser
  svn_path:   


#  == Maintenance downtime == 
#  Use to make the site unavailable to all but one ip
#  Just comment the lines out to operate the site normally. Note that this will need to be your public ip address.
#  Redirect gives an address to redirect all requests to.
#
#maintenance: 
#  ip:       123.456.7.8
#  redirect: holding

