environment: development
route:
 default:page

development:
 db:
  dbtype: mysql
  host: localhost
  port: 3306
  database: wax
  username: wax
  password: wax
 email:  
  host: localhost
  allowed_addresses: 
    
# The following will override values in development.
# If the values are the same there is no need to declare them.

test:
  db:
    database: test

production: 
  db: 
    database: wax

users:
  joet: password
