#!/bin/sh
PHP=`which php`
exec $PHP -C -q -d output_buffering=1 "$0" "$@"
<?php
//
//
// Web-site 		http://php-wax.com/
// Project	http://dev.php-wax.com/
//

ob_end_clean(); // make output from autofind php code disapear

/** 
 * PHP-WAX Project generation script
 * requires svn to be available from the command line
 */


$command = "svn export svn://php-wax.com/svn/main/trunk/skel/ ./".$argv[1]."/";
system($command);
die("PHP-WAX application for ".$argv[1]." setup complete"."\n");

?>
