#!/usr/bin/php
<?php

require_once dirname(__FILE__).'/../app/config/environment.php';

AutoLoader::include_dir(FRAMEWORK_DIR);
$configFile=APP_DIR.'config/config.yml';
$config_array = Spyc::YAMLLoad($configFile);
if(isset($argv[1]) && $argv[1]=="test" || $argv[1] == "production") {
	$config_array['environment']=$argv[1];
	unset($argv[1]);
}
$config_array = WXConfigBase::merge_environments($config_array);
WXConfigBase::set_instance();
$conf=new WXConfigBase;
$conf->init_db($config_array['db']);

if($argv[1] =="directory" && isset($argv[2])) {
  $migrate = new WXMigrate();
  $dir = "up";
  if(isset($argv[3])) $dir="down";
  $result = $migrate->version_less_migrate($argv[2]); 
  exit($result."\n");
} 


$dbdir = dirname(__FILE__).'/../app/db/migrate/';
if(!is_dir($dbdir)) {
  $command = "mkdir -p $dbdir";
  system($command);
}
$version = false;
if(isset($argv[1])) {
  $version = $argv[1];
}

$migrate = new WXMigrate;
if($version == 'version') {
  exit("Now at version ".$migrate->get_version()."\n");
}
if($version == 'clean') {
  $result = $migrate->migrate_revert($dbdir);
  exit("Database reset to version ".$result."\n");
}
$result = $migrate->migrate($dbdir, $version);
if($result===false) {
  exit("No Files to migrate". "\n");
}
exit("-------------------"."\n"."Successfully migrated to version ".$result."\n"."-------------------"."\n");

?>