#!/bin/sh
PHP=`which php`
exec $PHP -C -q -d output_buffering=1 "$0" "$@"
<?php
ob_end_clean(); // make output from autofind php code disapear
require_once dirname(__FILE__).'/../app/config/environment.php';
$gen = new WXGenerator("test", array_slice($argv, 1));
?>