#!/usr/bin/php
<?php
if(!isset($argv[1]) ) {
  exit("[ERROR] You must supply an Email Class name that you wish to create. 
");
}
$modeldir = dirname(__FILE__).'/../app/model/';
$model_name = ucfirst($argv[1])."Email";
$content = "<?php
class {$model_name} extends WXEmail
{
	
}
?>
";
if(is_readable($modeldir.$model_name.".php")) {
  exit("[ERROR] Not written, a model of that name already exists.
");
}
$command = "echo ".'"'.$content.'"'." > ".$modeldir.$model_name.".php";
system($command);
echo "Email class created in app/model.
";

?>