#!/bin/sh
PHP=`which php`
exec $PHP -C -q -d output_buffering=1 "$0" "$@"
<?php
require_once dirname(__FILE__).'/../app/config/environment.php';
Autoloader::run_application("development", false);
$gen = new WXGenerator("model", array_slice($argv, 1));
?>