#!/usr/bin/php
<?php
if(!isset($argv[1]) ) {
  exit("[ERROR] You must supply a model name that you wish to create. 
");
}
require_once dirname(__FILE__).'/../app/config/environment.php';
AutoLoader::include_dir(FRAMEWORK_DIR);
$modeldir = dirname(__FILE__).'/../app/model/';
$model_name = WXInflections::camelize($argv[1], true);
$content = "<?php
class {$model_name} extends WXActiveRecord
{
	
}
?>
";
if(is_readable($modeldir.$model_name.".php")) {
  exit("[ERROR] Not written, a model of that name already exists.
");
}
$command = "echo ".'"'.$content.'"'." > ".$modeldir.$model_name.".php";
system($command);
echo "Model class created in app/model.
";
?>