#!/usr/bin/php
<?php
require_once dirname(__FILE__).'/../app/config/environment.php';
$plugin_array = array(
  "cms"=>"svn://svn.webxpress.com/home/SVN/plugins/cms/"
);
if(!isset($argv[1]) ) {
  exit("[ERROR] You must supply a plugin name that you wish to install. 
Type 'script/plugin_install list' to see available plugins.
");
}
if($argv[1]=="list") {
  echo "The following plugins are available
";
  foreach($plugin_array as $plugin=>$location) {
    echo $plugin."
";
  }
  exit;
}
if(!array_key_exists($argv[1], $plugin_array)) {
  exit("[ERROR] Plugin not found.
Type 'script/plugin_install list' to see available plugins.
");
}
$source = $plugin_array[$argv[1]];
$output_dir = WAX_ROOT."plugins/".$argv[1]."/";
echo "This will overwrite files inside the plugins directory. Do you want to continue?: [y/n] ";
$answer = trim(fgets(STDIN));
if($answer != "y" && $answer != "yes") {
 exit("\n"); 
}
$command = "svn export {$source} {$output_dir} --force";
system($command);

echo "Plugin installed in /plugins/{$argv[1]}."."\n";
if(is_readable(WAX_ROOT."plugins/".$argv[1]."/installer")) {
  echo "Would you like to run the additional installer script: [y/n] ";
}
$answer = trim(fgets(STDIN));
if($answer != "y" && $answer != "yes") {
 exit("\n"); 
}
?>