#!/usr/bin/php
<?php
error_reporting(E_ALL ^ E_WARNING ^ E_NOTICE);
require_once dirname(__FILE__).'/../app/config/environment.php';
require_once 'wax/AutoLoader.php';
define("CLI_ENV", true);
AutoLoader::include_dir(FRAMEWORK_DIR);
set_exception_handler('throw_wxexception');
set_error_handler('throw_wxerror', 0);
if( (!include 'simpletest/unit_tester.php') || (!include 'simpletest/reporter.php')) {
  throw new WXDependencyException("Simpletest library required. Install it somewhere in the include path", "Simpletest Dependency Failure");
}


$configFile=APP_DIR.'config/config.yml';
$config_array = Spyc::YAMLLoad($configFile);
$config_array['environment']="test";
$config_array = WXConfigBase::merge_environments($config_array);
WXConfigBase::set_instance();
$conf=new WXConfigBase;
$conf->init_db($config_array['db']);
AutoLoader::include_dir(MODEL_DIR);
AutoLoader::include_dir(CONTROLLER_DIR);
self::include_from_registry('WXInflections');  // Bit of a hack -- forces the inflector functions to load
self::include_from_registry('WXHelpers');  // Bit of a hack -- forces the helper functions to load
if($argv[1] && is_dir(PLUGIN_DIR.$argv[1]."/tests")) {
  $testdir = PLUGIN_DIR.$argv[1]."/tests";
} else {
  $testdir = APP_DIR."tests";
}
AutoLoader::include_dir($testdir);
$test = new GroupTest('All tests');
foreach(scandir($testdir) as $file) {  	 
  if(substr($file, -3)=="php" && substr($file,0,1)!=".") { 
    $class = substr($file, 0,-4);	
    $test->addTestClass($class); 	 
  } 	 
}

$test->run(new TextReporter());
?>