#!/usr/bin/php
<?php
if(!isset($argv[1]) && !isset($argv[2])) {
  exit("[ERROR] You must supply at least two values, a model and a method"."\n");
}
require_once dirname(__FILE__).'/../app/config/environment.php';

AutoLoader::include_dir(FRAMEWORK_DIR);
$configFile=APP_DIR.'config/config.yml';
$config_array = Spyc::YAMLLoad($configFile);
$config_array = WXConfigBase::merge_environments($config_array);
WXConfigBase::set_instance();
$conf=new WXConfigBase;
$conf->init_db($config_array['db']);
if(!$model = new ucfirst(WXActiveRecord::camelize($argv[1]))) {
  exit("[ERROR] Cannot find class name given"."\n");
}
$method = $argv[2];
array_shift($argv);
array_shift($argv);
array_shift($argv);
$arguments = implode(", ", $argv);
if($model->$method($arguments) ) {
  exit("...successfully ran command"."\n");
} else {
  exit("[ERROR] Problem running command"."\n");
}
?>