#!/bin/sh
PHP=`which php`
exec $PHP -C -q -d output_buffering=1 "$0" "$@"
<?php
ob_end_clean(); // make output from autofind php code disapear
if(!isset($argv[1]) || !isset($argv[2])) {
  exit("[ERROR] You must supply at least two values, a model and a method"."\n");
}
require_once dirname(__FILE__).'/../app/config/environment.php';

$model_name = ucfirst(WXActiveRecord::camelize($argv[1]));
if(!class_exists($model_name) || !$model = new $model_name) {
  exit("[ERROR] Cannot find class name $model_name"."\n");
}
$commands = array($argv[1], $argv[2]);
array_shift($argv);
array_shift($argv);
array_shift($argv);

if(call_user_func_array($commands, $argv) ) {
  exit("...successfully ran command, and method returned true."."\n");
} else {
  exit("...successfully ran command but method returned false."."\n");
}
?>